---
title: "YouTube"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## Preview

```{r, echo = FALSE, hide = TRUE, message = FALSE, warning = FALSE}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
yaml <- yaml::read_yaml(file.path(root_dir, "_config_automation.yml"))

## For Youtube
youtube <- readr::read_tsv(file.path("metricminer_data", "youtube", "youtube.tsv"))
```

```{r eval=FALSE}
# Manual read of YouTube views. Local use only and can likely be deleted once we have all the links for the API!
yt_views <- googlesheets4::read_sheet(
  "https://docs.google.com/spreadsheets/d/1rV2bQOoOFxpC3izPdwhH3ph6FZ_aVdX9YHKWkNdZqZE/edit?gid=0#gid=0",
  sheet = 1
)
yt_views$cumsum <- cumsum(yt_views$Views)
make_yt_views_plot(yt_views)

```


## Data information

- `viewCount` how many times has the video been viewed?
- `likeCount` how many times has the video been liked?
- `dislikeCount` - how many times has the video been disliked?
- `favoriteCount` - how many times has the video been favorited?
- `commentCount` - how many comments on the video?

```{r}
knitr::kable(youtube)
```
